FROM centos:lastest

MAINTAINER frank <dengpan@mycapital.net>

WORKDIR /root/project/package

RUN yum update \
&&  yum install -y https://centos7.iuscommunity.org/ius-release.rpm \
&&  yum install -y python35u python35u-libs python35u-devel python35u-pip \
&&  yum install -y gcc gcc-c++ make unzip \
&&  pip3.5 install pip -U \
&&  pip3.5 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

RUN wget https://wiki.mycapital.net/mycapital/upload/my-platform-src.zip \
    unzip my-platform-src.zip \
    pip3.5 install ./*.tar.gz \
    echo "unzip demo_strategy.zip && cd demo_strategy && python3.5 st.py && python3.5 compile.py st.py" > test.sh
    
